---
- name: Configure pgbouncer.ini
  template:
    src: "pgbouncer.ini.j2"
    dest: "{{ pgbouncer_config_path | default(__pgbouncer_config_path) }}"
    owner: postgres
    group: root
    mode: 0640

- name: Configure pgbouncer pg_auth
  template:
    src: "pg_auth.j2"
    dest: "{{ pgbouncer_pg_auth | default(__pgbouncer_pg_auth) }}"
    owner: postgres
    group: root
    mode: 0640
  notify: restart pgbouncer


