---
- name: Configure pgbouncer.ini
  template:
    src: "pgbouncer.ini.j2"
    dest: "{{ pgbouncer_config_path }}"
    owner: postgres
    group: root
    mode: 0640

- name: Configure pgbouncer pg_auth
  template:
    src: "pg_auth.j2"
    dest: "{{ pgbouncer_pg_auth }}"
    owner: postgres
    group: root
    mode: 0640

- name: restart pgbouncer
  service:
    name: "{{ pgbouncer_daemon }}"
    state: restarted
    sleep: 5

